### ISSUE TITLE
无法登录，403报错

### ISSUE THREAD

**Issue by CoolerProYT** [KanadeSiina/pocket48-discord#4]
CmdError [cmdError]: Illegal operation or no permission
    at genCmdError (D:\JS\pocket48-discord\node_modules\nim-web-sdk-ng\dist\NIM_BROWSER_SDK.js:2883:40)
    at parseCmd (D:\JS\pocket48-discord\node_modules\nim-web-sdk-ng\dist\NIM_BROWSER_SDK.js:2884:10)
    at ClientSocket.onMessage (D:\JS\pocket48-discord\node_modules\nim-web-sdk-ng\dist\NIM_BROWSER_SDK.js:4105:21)
    at BaseWebsocket.emit (D:\JS\pocket48-discord\node_modules\nim-web-sdk-ng\dist\NIM_BROWSER_SDK.js:1237:37)
    at BaseWebsocket.onMessage (D:\JS\pocket48-discord\node_modules\nim-web-sdk-ng\dist\NIM_BROWSER_SDK.js:3727:30)
    at WebSocket.invokeTheCallbackFunction (D:\JS\pocket48-discord\node_modules\jsdom\lib\jsdom\living\generated\EventHandlerNonNull.js:14:28)
    at WebSocket.<anonymous> (D:\JS\pocket48-discord\node_modules\jsdom\lib\jsdom\living\helpers\create-event-accessor.js:35:32)
    at innerInvokeEventListeners (D:\JS\pocket48-discord\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:350:25)
    at invokeEventListeners (D:\JS\pocket48-discord\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:286:3)
    at WebSocketImpl._dispatch (D:\JS\pocket48-discord\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:233:9) {
  data: {},
  code: 403,
  cmd: 'login',
  timetag: 1716617131771,
  callFunc: 'parseCmd'
}

**Comment by akamya997** [comment]
我自己的也挂了，稍微排查了一下感觉非常神秘，突然就login不上了。
等下想想办法

**Comment by akamya997** [comment]
@CoolerProYT 
好像是新增了端末的检查，导致原本的代码没办法通过验证
最新的代码应该修复了

**Comment by akamya997** [comment]
好像正好是两周之前出现的问题，主要参考了
https://github.com/duan602728596/qqtools/commit/54c62a6f0c7aee6c364f34e7dbb9b7f9fc49af24

**Comment by akamya997** [comment]
好像还没完全修好，正在进行测试...

**Comment by CoolerProYT** [comment]
好的，大佬加油，我实在搞不懂怎么修

**Comment by akamya997** [comment]
虽然不知道发生了什么但暂时好像可用了

**Comment by CoolerProYT** [comment]
好的，辛苦了

**Comment by akamya997** [comment]
一段时间没出现问题，先把这个issue关了
